"""added text to catalog

Revision ID: 4bba7209be6f
Revises: 007cf100de9a
Create Date: 2019-04-23 12:12:43.611559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bba7209be6f'
down_revision = '007cf100de9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'text')
    # ### end Alembic commands ###
